// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ399vvxtzLzEbmkCBiGz05OYz_8jeiqI',
    appId: '1:915985952672:web:7969db36dcfcc6406c7ec5',
    messagingSenderId: '915985952672',
    projectId: 'flutter-ecommerce24',
    authDomain: 'flutter-ecommerce24.firebaseapp.com',
    storageBucket: 'flutter-ecommerce24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFNbWGDRVuqI6PrPjVFfNg4TfmXxpCBoY',
    appId: '1:915985952672:android:48fe4f76e5161b276c7ec5',
    messagingSenderId: '915985952672',
    projectId: 'flutter-ecommerce24',
    storageBucket: 'flutter-ecommerce24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtcVgENjEiyJuXNhZaW9n479pwSJ8gl3k',
    appId: '1:915985952672:ios:0a9bb59283f5a5d06c7ec5',
    messagingSenderId: '915985952672',
    projectId: 'flutter-ecommerce24',
    storageBucket: 'flutter-ecommerce24.appspot.com',
    iosClientId:
        '915985952672-9mvqa97i4u3lh6k70ns9dlqm0kisj8m0.apps.googleusercontent.com',
    iosBundleId: 'com.ecommerce.app',
  );
}
